### PR TITLE
Add a script for running the tests

### PR DESCRIPTION
**Pull request by robyoung**
Manages sets of environment variables in a directory. Create a file in `scripts/envs` called `{ environment }.sh` with all the environment variable exports then to use it run `./scripts/run_tests.sh {
environment }`.

### CODE REVIEW

**Comment by pcraig3** [comment]
Do we care which family of environment variables we're using?
For example, `DM_ADMINISTRATORNAME` (also) became `DM_ADMIN_EMAIL` in [an earlier pull request](https://github.com/alphagov/digitalmarketplace-functional-tests/commit/c61c155f97e1e951b360b2102206ee1f350fc01f), and the [README](https://github.com/alphagov/digitalmarketplace-functional-tests/blob/master/README.md) was updated to refer only to the new ones. 

/

Seems like two variables are missing from `example.sh`:
 - `DM_FRONTEND_DOMAIN`
 - `DM_SUPPLIER2_USER_EMAIL`

/ 

Finally, do you think it's worth adding a variable to specify only running one `.feature` file?  If I only wanted to run the admin journey, for example, it might come in useful.

**Comment by robyoung** [comment]
Good spot, I've changed them, thanks.

**Comment by robyoung** [comment]
With regard to allowing specific tags / features to be targeted; yes, maybe, I'm not sure of the most convenient way of doing it yet though. I was going to get this in and leave that for a later update.

**Comment by pcraig3** [comment]
:+1:

**Pull request merged**
