### PR TITLE
Content change for direct award skeleton

### PR DESCRIPTION
**Pull request by samuelhwilliams**
## Summary
Content changed for the direct award skeleton late in the game and I forgot to update the text here. Oops.

### CODE REVIEW

**Comment by MuriloDalRi** [comment]
👍

**Comment by TheDoubleK** [comment]
Please can we enter something that doesn't have the word "procurement" in it?

**Comment by TheDoubleK** [comment]
Thanks :)

**Comment by samuelhwilliams** [comment]
Yes. We can.

**Pull request merged**
