### PR TITLE
276-extra-func-tests-for-supplier-sign-up-w-duns

### PR DESCRIPTION
**Pull request by benvand**
* Add more tests for supplier registration flow with duns number check
  * Create account
  * Duns in use
  * Duns not found

https://trello.com/c/5EjhJ351/276-extra-func-tests-for-supplier-sign-up-w-duns

Run and working against preview

### CODE REVIEW

**Comment by katstevens** [comment]
I'm having trouble testing this with local `dmrunner` as the external D&B request from the Docker image is blocked on my machine. We may have to figure out a way of stubbing out the endpoint when running locally.

Would we need something like this to run the fallback scenario anyway? We are keeping the old scenario in case D&B is unavailable - how will that test pass the moment?

**Comment by benvand** [comment]
Yes we're keeping the old flow in case D&B is unavailable

**Comment by lfdebrux** [comment]
> I'm having trouble testing this with local `dmrunner` as the external D&B request from the Docker image is blocked on my machine. We may have to figure out a way of stubbing out the endpoint when running locally.
> 
> Would we need something like this to run the fallback scenario anyway? We are keeping the old scenario in case D&B is unavailable - how will that test pass the moment?

I can't reproduce on my machine, connection to Dun and Bradstreet from supplier frontend seems to work for me.

**Comment by lfdebrux** [comment]
Running these against dmrunner works for me.

**Pull request merged**
