### PR TITLE
Add tests for creating a draft requirement for all lots

### PR DESCRIPTION
**Pull request by CrystalPea**
Trello card: https://trello.com/c/cAcMOYus/708-functional-test-buyer-creating-a-draft-requirement

Superseded legacy test: https://github.com/alphagov/digitalmarketplace-functional-tests/blob/jenkins/features/buyer/buyer_create_requirements.feature#L8

### CODE REVIEW

**Comment by alext** [comment]
@CrystalPea I don't think you meant me...

**Comment by CrystalPea** [comment]
@alext you're totally right, it was a misclick and I have rectified it after a few seconds but I guess Github has sent an email to you already 😅

**Comment by CrystalPea** [comment]
@idavidmcdonald 
Thanks for commenting. I thought we discussed this before writing this test and then the conclusion was that `And I have created an individual specialist requirement` is a bit different since it creates the draft by direct API call instead of clicking through from the homepage. This test checks if links on homepage work and if creating the draft by clicking links and filling in the fields works. Is this checked elsewhere?

**Comment by idavidmcdonald** [comment]
Sorry, that was my assumption based on the step name but I was wrong. When I looked a bit further just now it turns out it does go through the form

https://github.com/alphagov/digitalmarketplace-functional-tests/blob/835df382a031b4c27b089cdd418a9c079e00a5b8/features/step_definitions/requirements_steps.rb#L5

**Pull request closed without merging**
