### PR TITLE
Update companies house link

### PR DESCRIPTION
**Pull request by TheDoubleK**
The URL changed in this story: https://www.pivotaltracker.com/story/show/133592011

### CODE REVIEW

**Comment by allait** [comment]
👍

**Comment by TheDoubleK** [comment]
Nice work me :+1:

**Comment by andrewchong** [comment]
👍 Go for it

**Comment by pcraig3** [comment]
👍  [Looks good, Kev](http://i3.kym-cdn.com/entries/icons/facebook/000/000/128/slowpoke_pokemon.jpg)!

**Pull request merged**
