### PR TITLE
Use autocomplete step for supplier account feature

### PR DESCRIPTION
**Pull request by lfdebrux**
This can be merged once alphagov/digitalmarketplace-supplier-frontend#1394 is on preview.

### CODE REVIEW

**Comment by lfdebrux** [comment]
I've tested this PR locally and against staging.

**Comment by domoscargin** [comment]
Ah, I was going to ask if this would just work by changing to using "Country" instead of "location-autocomplete" as a locator, but I see the hardcoded template has that a `span`, not a `label`, so it fails to find it.

Will merge the branch.

**Comment by lfdebrux** [comment]
> Ah, I was going to ask if this would just work by changing to using "Country" instead of "location-autocomplete" as a locator, without all the @Skip stuff, but I see the old hardcoded template has "Country" inside a span, not a label, so it fails to find it.

Oh, yeah, I should have mentioned that in the commit message. Super annoying.

**Review by domoscargin — APPROVED** [review]
https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1394 is merged

**Pull request merged**
