### PR TITLE
Add answer to `employmentStatus` question

### PR DESCRIPTION
**Pull request by alex9smith**
This question was added to Lots 1 & 2 of DOS in https://github.com/alphagov/digitalmarketplace-frameworks/pull/685

Add an answer in our fixtures so the automated tests can create valid briefs.

### CODE REVIEW

**Review by bjgill — APPROVED** [review]

**Review by bjgill — COMMENTED** [review]
Is this going to break production when we merge it?

**Comment by alex9smith** [comment]
Hmm actually yes it will. I'll revert the API change and have a think about how best to release

**Comment by gidsg** [comment]
@alex9smith could we use `@skip-staging` & `@skip-production` tags to roll this out to the tests gradually at the appropriate time?

**Comment by gidsg** [comment]
@alex9smith could we use `@skip-staging` & `@skip-production` tags to roll this out to the tests gradually at the appropriate time?

**Comment by gidsg** [comment]
@alex9smith Could we use the `@skip-staging` and `@skip-production` to roll this out gradually?

**Comment by alex9smith** [comment]
We _could_, but that'd mean skipping all the scenarios that involve creating, viewing or responding to a brief. I'm not sure that's a good idea since that's exactly the part of the system we're changing by adding a new question. 

I think the solution of making the question

**Comment by alex9smith** [comment]
Once we have released https://github.com/alphagov/digitalmarketplace-api/pull/1146 and https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/447 this will be safe to merge again. See the description on the API PR for the explanation why.

**Pull request merged**
